default_config:

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/custom-icons/custom-icons.js
    - /local/heating-schedule-card/heating-schedule-card.js

homeassistant:
  packages: !include_dir_named packages
  customize:
    binary_sensor.ku_fenstergruppe_01:
      device_class: window
    binary_sensor.wz_fenstergruppe_01:
      device_class: window
    binary_sensor.ki_fenstergruppe_01:
      device_class: window

automation: !include automations.yaml

climate:
  - platform: climate_group
    name: WZ_Heizungsgruppe_01
    entities:
      - climate.wz_heizung_01
      - climate.wz_heizung_02
  - platform: climate_group
    name: KI_Heizungsgruppe_01
    entities:
      - climate.ki_heizung_01
      - climate.ki_heizung_02

http:
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

shell_command:
  git_push_config: 'cd /config && git add -A && git diff --cached --quiet || (git commit -m "auto-update $(date +%Y-%m-%d_%H:%M)" && git push)'